openapi: 3.1.0
info:
  version: 1.0.0
  title: Schuster API Docs
  summary: This is a documentation for the Piperun Focco API
tags:
  - name: Auth
    description:
      $ref: ./auth/auth.md
  - name: Budget
    description: Budget operations.
  - name: Customer
    description: Customer operations.
  - name: PDF
    description: Generate PDFs.
servers:
  - url: "https://18.214.244.155.nip.io/api"
paths:
  /budgets/:id:
    $ref: paths/GetBudgetById.yaml
  /budgets/add:
    $ref: paths/CreateBudget.yaml
  /budget/request/:id:
    $ref:
  /budget/update:
    $ref: paths/UpdateBudgets.yaml
  /budget/payment-terms:
    $ref: paths/PaymentTerms.yaml
  /budget/deleteItem/:id:
    $ref: paths/DeleteItemById.yaml
  /v2/budget/add:
    $ref: paths/CreateBudgetV2.yaml
  /budgets/:
    $ref: paths/SearchBudgets.yaml
  /v2/budgets/:
    $ref: paths/SearchBudgetsV2.yaml
  
  /generate-pdf:
    $ref: paths/GeneratePdf.yaml
components:
  securitySchemes:
    main_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: "http://example.com/api/oauth/dialog"
          scopes:
            "read:users": read users info
            "write:users": modify or remove users
    Token:
      type: apiKey
      in: header
      name: Token
